ARG ES_VERSION=8.15.0

FROM docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}

COPY jmorphy2-elasticsearch/build/distributions/analysis-jmorphy2-*.zip /tmp/jmorphy2-plugin.zip

RUN elasticsearch-plugin install --batch file:///tmp/jmorphy2-plugin.zip
